name: investment_calculator
description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  easy_dynamic_theme: ^2.2.0
  flutter_rating_bar: ^4.0.0
  math_expressions: ^2.1.1
  intl: ^0.19.0
  currency_text_input_formatter: ^2.2.3
  pdf: ^3.5.49
  open_file: ^3.2.1
  path_provider: ^2.0.10
  permission_handler: ^11.3.1
  url_launcher: ^6.0.20
  mailer: ^6.1.0
  twilio_flutter: 0.3.0
  webview_flutter: ^4.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf

  assets:
    - assets/SIP.jpg
    - assets/fd.jpg
    - assets/emi.png
    - assets/swp.png
    - assets/ppf.png
    - assets/lumpsum.png
    - assets/gst.jpg
    - assets/maths.png
    - assets/percentage.png
    - assets/bmi.png
    - assets/gpa.png
    - assets/conversion.png
    - assets/scientific.png
    - assets/age.png
    - assets/si.png
    - assets/factorial.png
    - assets/pc.png
    - assets/exponent.png
    - assets/probability.png
    - assets/savings.png
    - assets/log.png
    - assets/currency.png
    - assets/fonts/Raleway-Regular.ttf
    - assets/average.png
    - assets/calender.png
    - assets/instagram.png
    - assets/linkedin.png
    - assets/github.png
    - assets/example.png
    - assets/credly.png
    - assets/cloud.png
    - assets/soham.jpg
    - assets/soham.gif
